# Pandas Tutotrial

- allows us to analyze big data

- can clean messy data sets, and make them readable and relevant.

- powerful data manipulation and analysis library for Python.

In [5]:
#pip install pandas
#pip install numpy

- Import Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = [1, 7, 2]
myvar = pd.Series(a)
myvar

0    1
1    7
2    2
dtype: int64

In [4]:
s =  pd.Series([1,2,3,4,5,np.nan,6,7,8,9])
s

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [5]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [9]:
df = pd.DataFrame(np.random.randn(6,4),columns=list("ABCD"), index = dates)#, index = dates, columns=list("ABCD")
df

                   A         B         C         D
2013-01-01  1.074638 -1.404819 -0.267572 -0.814313
2013-01-02 -0.635391 -0.366573 -0.458659 -0.307630
2013-01-03  0.974600 -0.427136 -0.801249 -1.214353
2013-01-04 -0.179675  0.322515  1.045840 -0.634020
2013-01-05 -1.881171  0.686364 -0.463981  0.141492
2013-01-06  1.599469 -0.255345  0.498680 -0.218988

In [10]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20220102"),
        "C": pd.Series(1, index = list(range(4)), dtype= "float32"),
        "D": np.array([3]*4, dtype="int32"),
        "E": pd.Categorical(["girl", "woman", "girl", "woman"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2022-01-02  1.0  3   girl  foo
1  1.0 2022-01-02  1.0  3  woman  foo
2  1.0 2022-01-02  1.0  3   girl  foo
3  1.0 2022-01-02  1.0  3  woman  foo

In [11]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [12]:
df.head(3)

                   A         B         C         D
2013-01-01  1.074638 -1.404819 -0.267572 -0.814313
2013-01-02 -0.635391 -0.366573 -0.458659 -0.307630
2013-01-03  0.974600 -0.427136 -0.801249 -1.214353

In [13]:
df.tail(2)

                   A         B         C         D
2013-01-05 -1.881171  0.686364 -0.463981  0.141492
2013-01-06  1.599469 -0.255345  0.498680 -0.218988

In [15]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [16]:
df.to_numpy()

array([[ 1.07463842, -1.40481866, -0.26757218, -0.81431338],
       [-0.63539106, -0.36657337, -0.45865947, -0.30763012],
       [ 0.97460026, -0.42713584, -0.80124867, -1.21435288],
       [-0.17967518,  0.32251502,  1.04583999, -0.6340198 ],
       [-1.88117093,  0.68636422, -0.4639812 ,  0.14149236],
       [ 1.59946881, -0.25534543,  0.49868031, -0.21898825]])

In [17]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.158745 -0.240832 -0.074490 -0.507969
std    1.302813  0.718700  0.699773  0.480450
min   -1.881171 -1.404819 -0.801249 -1.214353
25%   -0.521462 -0.411995 -0.462651 -0.769240
50%    0.397463 -0.310959 -0.363116 -0.470825
75%    1.049629  0.178050  0.307117 -0.241149
max    1.599469  0.686364  1.045840  0.141492

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2013-01-01 to 2013-01-06
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes

In [19]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.074638   -0.635391    0.974600   -0.179675   -1.881171    1.599469
B   -1.404819   -0.366573   -0.427136    0.322515    0.686364   -0.255345
C   -0.267572   -0.458659   -0.801249    1.045840   -0.463981    0.498680
D   -0.814313   -0.307630   -1.214353   -0.634020    0.141492   -0.218988

In [21]:
df.sort_values(by ="A", ascending=True)

                   A         B         C         D
2013-01-05 -1.881171  0.686364 -0.463981  0.141492
2013-01-02 -0.635391 -0.366573 -0.458659 -0.307630
2013-01-04 -0.179675  0.322515  1.045840 -0.634020
2013-01-03  0.974600 -0.427136 -0.801249 -1.214353
2013-01-01  1.074638 -1.404819 -0.267572 -0.814313
2013-01-06  1.599469 -0.255345  0.498680 -0.218988

In [32]:
df["A"]

0    1.043239
1   -0.751923
2   -0.490733
3    1.639595
4   -1.156184
5   -1.449911
Name: A, dtype: float64

In [25]:
df[0:2]

                   A         B         C         D
2013-01-01  1.074638 -1.404819 -0.267572 -0.814313
2013-01-02 -0.635391 -0.366573 -0.458659 -0.307630

In [26]:
df.loc[dates[3]]

A   -0.179675
B    0.322515
C    1.045840
D   -0.634020
Name: 2013-01-04 00:00:00, dtype: float64

In [27]:
df.loc["20130101":"20130104",["A","B"]]

                   A         B
2013-01-01  1.074638 -1.404819
2013-01-02 -0.635391 -0.366573
2013-01-03  0.974600 -0.427136
2013-01-04 -0.179675  0.322515

In [28]:
df.at[dates[3],"A"]

-0.1796751776847428

In [29]:
df2 = df.copy()
df2

                   A         B         C         D
2013-01-01  1.074638 -1.404819 -0.267572 -0.814313
2013-01-02 -0.635391 -0.366573 -0.458659 -0.307630
2013-01-03  0.974600 -0.427136 -0.801249 -1.214353
2013-01-04 -0.179675  0.322515  1.045840 -0.634020
2013-01-05 -1.881171  0.686364 -0.463981  0.141492
2013-01-06  1.599469 -0.255345  0.498680 -0.218988

In [32]:
df2["New2"] = [1,2,3,4,5,6]
df2

                   A         B         C         D  New  New2
2013-01-01  1.074638 -1.404819 -0.267572 -0.814313    1     1
2013-01-02 -0.635391 -0.366573 -0.458659 -0.307630    2     2
2013-01-03  0.974600 -0.427136 -0.801249 -1.214353    3     3
2013-01-04 -0.179675  0.322515  1.045840 -0.634020    4     4
2013-01-05 -1.881171  0.686364 -0.463981  0.141492    5     5
2013-01-06  1.599469 -0.255345  0.498680 -0.218988    6     6

In [33]:
df2.mean()

A       0.158745
B      -0.240832
C      -0.074490
D      -0.507969
New     3.500000
New2    3.500000
dtype: float64

In [34]:
import pandas as pd
df = pd.read_csv('sample.csv')
df

   class    who
0  Third    man
1  First  woman
2  Third  woman
3  First  woman

- cleaning data
- cleaning emplty cells
- cleaning wrong data
- removing duplicates
- correlation