In [1]:
import pandas as pd

In [6]:
!pip install requests

Collecting requests
  Downloading requests-2.33.0-py3-none-any.whl.metadata (5.1 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.6-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.33.0-py3-none-any.whl (65 kB)
Downloading charset_normalizer-3.4.6-cp313-cp313-win_amd64.whl (154 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ------------------------ --------------- 3/5 [certifi]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.2.25 charset_normalizer-3.4.6 idna-3.11 requests-2.33.0 urllib3-2.6.3

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
#opening a CSV from URL
import requests
from io import StringIO

url = "https://gist.githubusercontent.com/kevin336/acbb2271e66c10a5b73aacf82ca82784/raw/employees.csv"
headers = {"User-Agent": "Mozillla/5.0 (Macintosh;Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox /66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [18]:
# Sep Parameter + name
pd.read_csv("./src/sample_5x20.tsv",sep='\t',names=['first','second','third','fourth','fifth'])

      first   second    third   fourth    fifth
0   Column1  Column2  Column3  Column4  Column5
1      R1C1     R1C2     R1C3     R1C4     R1C5
2      R2C1     R2C2     R2C3     R2C4     R2C5
3      R3C1     R3C2     R3C3     R3C4     R3C5
4      R4C1     R4C2     R4C3     R4C4     R4C5
5      R5C1     R5C2     R5C3     R5C4     R5C5
6      R6C1     R6C2     R6C3     R6C4     R6C5
7      R7C1     R7C2     R7C3     R7C4     R7C5
8      R8C1     R8C2     R8C3     R8C4     R8C5
9      R9C1     R9C2     R9C3     R9C4     R9C5
10    R10C1    R10C2    R10C3    R10C4    R10C5
11    R11C1    R11C2    R11C3    R11C4    R11C5
12    R12C1    R12C2    R12C3    R12C4    R12C5
13    R13C1    R13C2    R13C3    R13C4    R13C5
14    R14C1    R14C2    R14C3    R14C4    R14C5
15    R15C1    R15C2    R15C3    R15C4    R15C5
16    R16C1    R16C2    R16C3    R16C4    R16C5
17    R17C1    R17C2    R17C3    R17C4    R17C5
18    R18C1    R18C2    R18C3    R18C4    R18C5
19    R19C1    R19C2    R19C3    R19C4    R19C5
20    R20C1    R20C2    R20C3    R20C4    R20C5

In [16]:
df =pd.read_csv('./src/kashti.csv')
df

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
# index column
df =pd.read_csv('./src/kashti.csv',index_col='Unnamed: 0')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [25]:
#use_cols parameter
pd.read_csv('./src/kashti.csv',usecols=['survived','age','sex'])

     survived     sex   age
0           0    male  22.0
1           1  female  38.0
2           1  female  26.0
3           1  female  35.0
4           0    male  35.0
..        ...     ...   ...
886         0    male  27.0
887         1  female  19.0
888         0  female   NaN
889         1    male  26.0
890         0    male  32.0

[891 rows x 3 columns]

In [ ]:
# skip rows
pd.read_csv('.\src\salary_Data.csv',skiprows=[1,5])

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ABDULLAH\AppData\Local\Temp\ipykernel_10856\69844631.py:2: SyntaxWarning: invalid escape sequence '\s'
  pd.read_csv('.\src\salary_Data.csv',skiprows=[1,5])

    YearsExperience  Salary
0               1.3   46205
1               1.5   37731
2               2.0   43525
3               2.9   56642
4               3.0   60150
5               3.2   54445
6               3.2   64445
7               3.7   57189
8               3.9   63218
9               4.0   55794
10              4.0   56957
11              4.1   57081
12              4.5   61111
13              4.9   67938
14              5.1   66029
15              5.3   83088
16              5.9   81363
17              6.0   93940
18              6.8   91738
19              7.1   98273
20              7.9  101302
21              8.2  113812
22              8.7  109431
23              9.0  105582
24              9.5  116969
25              9.6  112635
26             10.3  122391
27             10.5  121872

In [35]:
#nrows
pd.read_csv('.\src\salary_Data.csv',nrows=10)

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ABDULLAH\AppData\Local\Temp\ipykernel_10856\3443574832.py:2: SyntaxWarning: invalid escape sequence '\s'
  pd.read_csv('.\src\salary_Data.csv',nrows=10)

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891
5              2.9   56642
6              3.0   60150
7              3.2   54445
8              3.2   64445
9              3.7   57189

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    str
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 92.4 KB

In [40]:
df['sibsp'] = df['sibsp'].astype(float)

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    float64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    str
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), float64(3), int64(3), str(7)
memory usage: 92.4 KB

In [48]:
# date by default coming in string have to convert it into date
pd.read_csv('.\src\salary_data.csv').info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64
 2   Date             30 non-null     str
dtypes: float64(1), int64(1), str(1)
memory usage: 852.0 bytes

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ABDULLAH\AppData\Local\Temp\ipykernel_10856\3014228855.py:2: SyntaxWarning: invalid escape sequence '\s'
  pd.read_csv('.\src\salary_data.csv').info()

In [51]:
pd.read_csv('.\src\salary_data.csv',parse_dates=['Date']).info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64
 2   Date             30 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1)
memory usage: 852.0 bytes

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ABDULLAH\AppData\Local\Temp\ipykernel_10856\1458089086.py:1: SyntaxWarning: invalid escape sequence '\s'
  pd.read_csv('.\src\salary_data.csv',parse_dates=['Date']).info()
C:\Users\ABDULLAH\AppData\Local\Temp\ipykernel_10856\1458089086.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.read_csv('.\src\salary_data.csv',parse_dates=['Date']).info()

In [ ]:
# defining NaNs in data
pd.read_csv('.\src\salary_data.csv',na_values=['na','-','_','0'])

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ABDULLAH\AppData\Local\Temp\ipykernel_10856\1108566133.py:1: SyntaxWarning: invalid escape sequence '\s'
  pd.read_csv('.\src\salary_data.csv',na_values=['na','-','_','0'])

    YearsExperience  Salary        Date  NA Values
0               1.1   39343  20/10/2022        NaN
1               1.3   46205  21/11/2022        1.0
2               1.5   37731  20/10/2023        2.0
3               2.0   43525  21/11/2023        3.0
4               2.2   39891  20/10/2024        NaN
5               2.9   56642  21/11/2024        NaN
6               3.0   60150  20/10/2025        NaN
7               3.2   54445  21/11/2025        NaN
8               3.2   64445  20/10/2026        NaN
9               3.7   57189  21/11/2026        NaN
10              3.9   63218  20/10/2027        NaN
11              4.0   55794  21/11/2027        3.0
12              4.0   56957  20/10/2028        4.0
13              4.1   57081  21/11/2028        5.0
14              4.5   61111  20/10/2029        6.0
15              4.9   67938  21/11/2029        7.0
16              5.1   66029  20/10/2030        8.0
17              5.3   83088  21/11/2030        9.0
18              5.9   81363  20/10/2031       10.0
19              6.0   93940  21/11/2031       11.0
20              6.8   91738  20/10/2032       12.0
21              7.1   98273  21/11/2032       13.0
22              7.9  101302  20/10/2033       14.0
23              8.2  113812  21/11/2033       15.0
24              8.7  109431  20/10/2034       16.0
25              9.0  105582  21/11/2034       17.0
26              9.5  116969  20/10/2035       18.0
27              9.6  112635  21/11/2035       19.0
28             10.3  122391  20/10/2036       20.0
29             10.5  121872  21/11/2036       21.0

In [68]:
# loading huge dataset in chunks
df = pd.read_csv('.\src\kashti.csv',chunksize=100)

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ABDULLAH\AppData\Local\Temp\ipykernel_10856\3659029193.py:2: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('.\src\kashti.csv',chunksize=100)

In [69]:
for chunks in df:
    print(chunks.shape)

(100, 16)
(100, 16)
(100, 16)
(100, 16)
(100, 16)
(100, 16)
(100, 16)
(100, 16)
(91, 16)

In [77]:
#converters
def rename (name):
    if name == 'male':
        return 'M'
    else:
        return name

In [78]:
#converters
pd.read_csv('.\src\kashti.csv',converters={'sex':rename})

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ABDULLAH\AppData\Local\Temp\ipykernel_10856\2074019808.py:2: SyntaxWarning: invalid escape sequence '\s'
  pd.read_csv('.\src\kashti.csv',converters={'sex':rename})

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,M,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,M,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,0,2,M,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,M,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,M,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True