In [1]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv("./src/orders.csv")
date

          date  product_id  city_id  orders
0   12/10/2019        5000       25      25
1   12/11/2019        5001       30      30
2   12/12/2019        5002       23      23
3   12/13/2019        5003       25      25
4   12/14/2019        5004       30      30
..         ...         ...      ...     ...
94   3/13/2020        5094       45       0
95   3/14/2020        5095       34       0
96   3/15/2020        5096       45       0
97   3/16/2020        5097       56       0
98   3/17/2020        5098       45       0

[99 rows x 4 columns]

In [4]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        99 non-null     str
 1   product_id  99 non-null     int64
 2   city_id     99 non-null     int64
 3   orders      99 non-null     int64
dtypes: int64(3), str(1)
memory usage: 3.2 KB

In [5]:
date['date'] =pd.to_datetime(date['date'])

In [6]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        99 non-null     datetime64[us]
 1   product_id  99 non-null     int64
 2   city_id     99 non-null     int64
 3   orders      99 non-null     int64
dtypes: datetime64[us](1), int64(3)
memory usage: 3.2 KB

In [7]:
#extracting the year, month and day from the date column
date['year'] = date['date'].dt.year
date['month'] = date['date'].dt.month
date['day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  year  month  day
0 2019-12-10        5000       25      25  2019     12   10
1 2019-12-11        5001       30      30  2019     12   11
2 2019-12-12        5002       23      23  2019     12   12
3 2019-12-13        5003       25      25  2019     12   13
4 2019-12-14        5004       30      30  2019     12   14

In [8]:
# extract month name from the date column
date['month_name'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  year  month  day month_name
0 2019-12-10        5000       25      25  2019     12   10   December
1 2019-12-11        5001       30      30  2019     12   11   December
2 2019-12-12        5002       23      23  2019     12   12   December
3 2019-12-13        5003       25      25  2019     12   13   December
4 2019-12-14        5004       30      30  2019     12   14   December

In [9]:
# day of the week - name
date['day_of_week'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,year,month,day,month_name,day_of_week
0,2019-12-10,5000,25,25,2019,12,10,December,Tuesday
1,2019-12-11,5001,30,30,2019,12,11,December,Wednesday
2,2019-12-12,5002,23,23,2019,12,12,December,Thursday
3,2019-12-13,5003,25,25,2019,12,13,December,Friday
4,2019-12-14,5004,30,30,2019,12,14,December,Saturday

In [ ]:
#day of the week - number
date['day_of_week_num'] = date['date'].dt.dayofweek # Monday = 0, Sunday = 6
date.head()

,date,product_id,city_id,orders,year,month,day,month_name,day_of_week,day_of_week_num
0,2019-12-10,5000,25,25,2019,12,10,December,Tuesday,1
1,2019-12-11,5001,30,30,2019,12,11,December,Wednesday,2
2,2019-12-12,5002,23,23,2019,12,12,December,Thursday,3
3,2019-12-13,5003,25,25,2019,12,13,December,Friday,4
4,2019-12-14,5004,30,30,2019,12,14,December,Saturday,5

In [11]:
# is inweekend?
date['is_weekend'] = date['day_of_week_num'].apply(lambda x: 1 if x >= 5 else 0)
date.head()

,date,product_id,city_id,orders,year,month,day,month_name,day_of_week,day_of_week_num,is_weekend
0,2019-12-10,5000,25,25,2019,12,10,December,Tuesday,1,0
1,2019-12-11,5001,30,30,2019,12,11,December,Wednesday,2,0
2,2019-12-12,5002,23,23,2019,12,12,December,Thursday,3,0
3,2019-12-13,5003,25,25,2019,12,13,December,Friday,4,0
4,2019-12-14,5004,30,30,2019,12,14,December,Saturday,5,1

In [12]:
# week of the year
date['week_of_year'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,year,month,day,month_name,day_of_week,day_of_week_num,is_weekend,week_of_year
0,2019-12-10,5000,25,25,2019,12,10,December,Tuesday,1,0,50
1,2019-12-11,5001,30,30,2019,12,11,December,Wednesday,2,0,50
2,2019-12-12,5002,23,23,2019,12,12,December,Thursday,3,0,50
3,2019-12-13,5003,25,25,2019,12,13,December,Friday,4,0,50
4,2019-12-14,5004,30,30,2019,12,14,December,Saturday,5,1,50

In [13]:
# extract quarter of the year
date['quarter'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,year,month,day,month_name,day_of_week,day_of_week_num,is_weekend,week_of_year,quarter
0,2019-12-10,5000,25,25,2019,12,10,December,Tuesday,1,0,50,4
1,2019-12-11,5001,30,30,2019,12,11,December,Wednesday,2,0,50,4
2,2019-12-12,5002,23,23,2019,12,12,December,Thursday,3,0,50,4
3,2019-12-13,5003,25,25,2019,12,13,December,Friday,4,0,50,4
4,2019-12-14,5004,30,30,2019,12,14,December,Saturday,5,1,50,4

In [ ]:
# extract semester of the year
date['semester'] = date['date'].dt.month.apply(lambda x: 1 if x <= 6 else 2) 
date.head()

,date,product_id,city_id,orders,year,month,day,month_name,day_of_week,day_of_week_num,is_weekend,week_of_year,quarter,semester
0,2019-12-10,5000,25,25,2019,12,10,December,Tuesday,1,0,50,4,2
1,2019-12-11,5001,30,30,2019,12,11,December,Wednesday,2,0,50,4,2
2,2019-12-12,5002,23,23,2019,12,12,December,Thursday,3,0,50,4,2
3,2019-12-13,5003,25,25,2019,12,13,December,Friday,4,0,50,4,2
4,2019-12-14,5004,30,30,2019,12,14,December,Saturday,5,1,50,4,2

In [15]:
#extract time elapsed between dates
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 4, 26, 16, 43, 36, 694582)

In [16]:
today - date['date']

0    2329 days 16:43:36.694582
1    2328 days 16:43:36.694582
2    2327 days 16:43:36.694582
3    2326 days 16:43:36.694582
4    2325 days 16:43:36.694582
                ...
94   2235 days 16:43:36.694582
95   2234 days 16:43:36.694582
96   2233 days 16:43:36.694582
97   2232 days 16:43:36.694582
98   2231 days 16:43:36.694582
Name: date, Length: 99, dtype: timedelta64[us]

In [18]:
(today - date['date']).dt.days

0     2329
1     2328
2     2327
3     2326
4     2325
      ...
94    2235
95    2234
96    2233
97    2232
98    2231
Name: date, Length: 99, dtype: int64

In [19]:
# months passed
(today - date['date']).dt.days / 30

0     77.633333
1     77.600000
2     77.566667
3     77.533333
4     77.500000
        ...
94    74.500000
95    74.466667
96    74.433333
97    74.400000
98    74.366667
Name: date, Length: 99, dtype: float64