In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [4]:
df = pd.read_csv('./src/kashti.csv')[['age','pclass','sibsp','parch','survived']]
df.head()

    age  pclass  sibsp  parch  survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [6]:
df.isnull().sum()

age         177
pclass        0
sibsp         0
parch         0
survived      0
dtype: int64

In [7]:
df.shape

(891, 5)

In [8]:
df.dropna(inplace=True)

In [9]:
df.shape

(714, 5)

In [10]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [11]:
x.head()

    age  pclass  sibsp  parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [13]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

### Feature Construction

In [14]:
x['family_size'] = x['sibsp'] + x['parch']+1
x.head()

    age  pclass  sibsp  parch  family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [15]:
def myfunc(num):
    if num == 1:
        return 0
    elif num >= 2 and num <= 4:
        return 1
    else:
        return 2

In [16]:
myfunc(4)

1

In [17]:
x['family_type'] = x['family_size'].apply(myfunc)
x.head()

    age  pclass  sibsp  parch  family_size  family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [18]:
x.drop(['sibsp','parch','family_size'],axis=1,inplace=True)
x.head()

    age  pclass  family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [19]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)